### ISSUE TITLE
blog list page styling

### ISSUE THREAD

**Issue by lukemiller** [CunningFolkDev/elevate360_website#10]
https://5b858a6b93a57a4734333f6c.preview.siteleaf.com/blog/

**Comment by cunning-folk** [comment]
Added to Zeplin.

I think the detail view is pretty much fine. She seems happy with it.

**Comment by cunning-folk** [comment]
Let's connect on the detail page. I like the copy width they have on Zeldman's blog. Nice leading on the letters and the width of the copy is easy to read

[Zeldman Medium](https://medium.com/@zeldman/lucky-he-said-my-glamorous-life-80c17e65f3b4)

**Comment by lukemiller** [comment]
we'll see how the images work out.  Let's have her put the image in a meta field which will give me a bit more control over styling it.  I'll change the existing ones (from inline to meta field).  That will also help put the image in the /blog view

**Comment by lukemiller** [comment]
done
