### ISSUE TITLE
Add 'Trainings' and 'Our Technology' to the top-level nav under 'Services'

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#100]

**Comment by cunning-folk** [comment]
@lukemiller after these sections are live, we'll need to get links to them via top-level nav.

**Comment by cunning-folk** [comment]
Does anyone have the capacity to work on this issue today? If we can get the top-level nav updated, I can buy some time to round out the other issues.

**Comment by lukemiller** [comment]
Yeah, I can do it in a bit

**Comment by gblakeman** [comment]
@lukemiller Just a heads-up: when you add the new items, you’ll need to adjust the `max-height` property for that section of the menu:

https://github.com/CunningFolkDev/elevate360_website/blob/master/_assets/css/elevate_theme/_layout.scss#L24

**Comment by lukemiller** [comment]
ready:

https://5b858a6b93a57a4734333f6c.preview.siteleaf.com/

**Comment by cunning-folk** [comment]
@lukemiller thanks man, I appreciate it!
