### ISSUE TITLE
Form option

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#101]

**Comment by cunning-folk** [comment]
@gblakeman does this seem like a good solution for a web form?

https://getform.io/

We'll need to move away from using mailchimp in the near future.

**Comment by gblakeman** [comment]
@cunning-folk Getform looks like it’ll work just fine. I’ve also had success with [Formcarry](https://formcarry.com) before. If there isn’t a preference, I’ll use the latter since the services seem virtually the same and I’m already familiar with it.

**Comment by cunning-folk** [comment]
I have no preference and I defer to you. Email should go to ‘
info@elevate360.com’

**Comment by gblakeman** [comment]
@cunning-folk I added the Formcarry credentials to the card in Projects.

**Comment by gblakeman** [comment]
The new contact form is `production`. It should be sending emails. They should also show up in the Formcarry dashboard for the “Elevate360 Website” form.
