### ISSUE TITLE
Services: Treatment Programs: “Download App” Link Missing

### ISSUE THREAD

**Issue by gblakeman** [CunningFolkDev/elevate360_website#121]
The “Download the App” button on the `/services/treatment-programs/` page is missing the download link.

Need to update `button_href` in `_layouts/services.html`.

<img width="1440" alt="screen shot 2018-12-06 at 11 58 02 am" src="https://user-images.githubusercontent.com/867428/49608718-36fb3c00-f94e-11e8-8353-6f2e590a3452.png">

**Comment by gblakeman** [comment]
@cunning-folk What should the “Download the App” link be? Right now it’s not going anywhere.

**Comment by cunning-folk** [comment]
@gblakeman I think this would be the safest bet for now. https://www.chess.health/download/
