### ISSUE TITLE
Section header in wrong place

### ISSUE THREAD

**Issue by jeremylenz** [CunningFolkDev/elevate360_website#126]
About Us page - On a very wide screen, I'm seeing the "Who We Are" section header in the wrong place (see screenshot)

**Comment by jeremylenz** [comment]
<img width="2448" alt="screen shot 2018-12-06 at 4 55 17 pm" src="https://user-images.githubusercontent.com/22042343/49614364-092aed00-f978-11e8-85d9-7ecc5abb7010.png">

**Comment by gblakeman** [comment]
@jeremylenz Lol, what screen is that? I couldn’t test anything wider than my iMac, so I must’ve missed that.

**Comment by jeremylenz** [comment]
The About Us page

**Comment by gblakeman** [comment]
@jeremylenz Haha, no, I meant: how wide was your browser? Screen size?

**Comment by gblakeman** [comment]
Nevemind, I can replicate it on my iMac. I’ll look into it.
