### ISSUE TITLE
Update Google Developer Platform Billing

### ISSUE THREAD

**Issue by gblakeman** [CunningFolkDev/elevate360_website#136]
Update the card on file for the Google Developer Account that is getting used for Google Maps integration.

Related to #95.

**Comment by gblakeman** [comment]
@cunning-folk Just a reminder for you, Peter, so that this task doesn’t get lost.

**Comment by cunning-folk** [comment]
Ya, I never got an email invite. I’ll do some digging on Monday.

**Comment by gblakeman** [comment]
@cunning-folk Hmm, weird. You might just need to go to [Google Cloud Console]
(https://console.cloud.google.com) and make sure you’re logged in with the email address you gave me to access it.

**Comment by cunning-folk** [comment]
@gblakeman the app wont let me add myself as a 'payments user' so I can then update the CC info. Thoughts?

https://console.cloud.google.com/billing
