### ISSUE TITLE
Layouts: Remove Redundancy from default + markdown

### ISSUE THREAD

**Issue by gblakeman** [CunningFolkDev/elevate360_website#138]
The `default.html` and `markdown.html` share a bunch of redundant code. Ideally there would be only one base layout (probably `default.html`) and `markdown.html` would inherit from it.

**Comment by gblakeman** [comment]
@jeremylenz As you take a look at this, feel free to review the other layouts too. They were all created at different times by multiple people, so don’t assume a coherent strategy existed. It may be possible to easily combine/share a few more layout files in a sensible way.

**Comment by jeremylenz** [comment]
I think by now the most egregious redundancies have been addressed.  Closing
