### ISSUE TITLE
YouTube Embeds?

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#169]

**Comment by cunning-folk** [comment]
@jeremylenz Do you know anything about posting YouTube HTML embeds into the Bios section of this website?

Do you have any time to research the best way to do this?

**Comment by jeremylenz** [comment]
I think it should be pretty straightforward. Youtube even provides embed code.

**Comment by cunning-folk** [comment]
@jeremylenz  About 2-3 hrs to post a few videos?

Just let me know how much time you need and I'll send the URLS.

Also, Elevate360 needs to do a rebrand and therefore a reskin of the website in the near future. I'll keep you appraised.

**Comment by jeremylenz** [comment]
Yeah that all sounds good!

--
Jeremy Lenz
646-248-6678
Github | Medium | LinkedIn | Twitter

**Comment by jeremylenz** [comment]
yes please! :)

--
Jeremy Lenz
646-248-6678
Github | Medium | LinkedIn | Twitter

**Comment by cunning-folk** [comment]
![staff interior youtube](https://user-images.githubusercontent.com/31627480/52592512-d253d600-2e03-11e9-8c5d-5380d2f1dca2.jpg)

@jeremylenz given that they are about to rebrand so lets just plop the youtube vid right under the bio copy. Sound ok?

**Comment by jeremylenz** [comment]
Sure, that will work just fine for now!  I can get started no later than tomorrow if that works.


--
Jeremy Lenz
646-248-6678
Github | Medium | LinkedIn | Twitter

**Comment by jeremylenz** [comment]
Ok, YouTube embeds and ZenCare links are up now.
