### ISSUE TITLE
Green Banner Height

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#17]
<img width="1127" alt="screen shot 2018-11-07 at 1 00 38 pm" src="https://user-images.githubusercontent.com/31627480/48157551-2becb780-e28d-11e8-9874-7d991537bbd9.png">

Can we please get the green (#b9c02f) banner narrower with the content centered within it?

Its about 233 height in the comp and @400 height on live website

**Comment by lukemiller** [comment]
done
