### ISSUE TITLE
SEO Enhancement

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#172]
@jeremylenz Here are the to-do's you outlined in our slack convo. Should I break these out into specific issues? 

You have approval to do the coding and I will use the CMS to enter the data.

**Comment by cunning-folk** [comment]
@jeremylenz our to-do list:
1. Add a <meta> Description tag to all layouts

2. Make sure there is a place in Siteleaf to put `seo_keywords` for all pages, and change the jekyll site to pick them up accordingly

3.  If we agree about the title thing, no changes should be needed. It already puts the `title` field in the <title> tag.

So after this is done,

the client will be able to add/edit `seo_keywords`, `title`, and `description` for all pages, and it will show up in the HTML in the correct places.

**Comment by jeremylenz** [comment]
@cunning-folk Ok I can get started on this tomorrow!  I think it can stay as a single issue.

**Comment by jeremylenz** [comment]
@cunning-folk The new metadata fields have been added and you should be able to edit them in Siteleaf now.  Lmk if any are missing etc.

**Comment by cunning-folk** [comment]
@jeremylenz is there anything I need to know about editing 'collections'?

or any other editing info? The client will be adding the data, so I want to set them up for success. Thanks very much!

**Comment by jeremylenz** [comment]
Hey Peter

The more technical explanation is in the linked pull request #173, but the basics for the client are:

* The three SEO metadata fields are `title`, `seo_keywords`, and `seo_description`.
* In Siteleaf, you edit these fields depending on which type of page it is:
  * For regular pages, edit the fields directly on the appropriate page in Siteleaf.
  * For pages which are the front page of a collection and don't show up in Siteleaf for editing*, go to the appropriate collection in Siteleaf and then go to 'Collection Settings.'  The metadata fields will show up there for editing.
  *  For pages which are the front page of a collection, but DO show up in Siteleaf for editing**, you can edit the fields directly on the appropriate page in Siteleaf.  No need to go to the collection settings.

\* in other words, pages that are `.html` files and have a value in front matter for `collection`
\*\* in other words, pages that are `.markdown` files and have a value in front matter for `collection`

The system will create `<title>` and `<meta>` tags as follows:
1. `<title>` tag - created from the `title` metadata field.
2. `<meta name="keywords">` tag - created in the document `<head>` from the `seo_keywords` metadata field.
3. `<meta name="description">` tag - created in the document `<head>` from the `seo_description` metadata field.

**Comment by jeremylenz** [comment]
@cunning-folk Update: It looks like Siteleaf deleted the `seo_keywords` and `seo_description` fields from `_config.yml` because they were blank.  So some of the fields that are supposed to show under "Collection Settings" may have disappeared.  You can just add them again in Siteleaf, or if it's easier I can just add all the content from the doc myself.. let me know.  Reopening the issue until everything is in place.

**Comment by cunning-folk** [comment]
hi @jeremylenz

Go ahead and enter the data

Thanks!

**Comment by jeremylenz** [comment]
@cunning-folk Data is entered; let me know if you see any issues!

**Comment by cunning-folk** [comment]
Awesome. I appreciate the help.
