### ISSUE TITLE
Need Favicon.ico for new logo

### ISSUE THREAD

**Issue by jeremylenz** [CunningFolkDev/elevate360_website#177]
Need to update our Favicon.ico with the new logo.

**Comment by jeremylenz** [comment]
_1. Can you update the tab icon from the E icon to the W icon (I think this is the favicon)_

**Comment by cunning-folk** [comment]
[favicon_package_v0.16.zip](https://github.com/CunningFolkDev/elevate360_website/files/3183877/favicon_package_v0.16.zip)

@jeremylenz let me know if this works for you.

**Comment by cunning-folk** [comment]
@jeremylenz just let me know exacting requirements for this piece. Thanks!

**Comment by cunning-folk** [comment]
[favicon_io.zip](https://github.com/CunningFolkDev/elevate360_website/files/3188504/favicon_io.zip)
@jeremylenz try this. hope it works!

**Comment by jeremylenz** [comment]
@cunning-folk Looks great on chrome!  Safari is still misbehaving.  I think it's using `safari-pinned-tab.svg`.  @gblakeman It's showing up half size and also I'm not sure how to force Safari to reload the favicon.  Do you know how to get it to behave?

**Comment by gblakeman** [comment]
@jeremylenz Are you talking about local dev? Or is this in production? Safari is really stubborn about caching this stuff. The only semi-reliable way I’ve found to force it to load a new one is  to empty the entire browser cache (`Develop > Empty Caches`). Not ideal.

Otherwise, in the production the updated filename should eventually cause Safari to show the new one.

I could be wrong, but I believe that if you have “Show website icons in tabs” enabled in the Safari preferences, it should give the `favicon` preference over the pinned tab.

**Comment by jeremylenz** [comment]
@gblakeman thanks for your help! (The issue was happening both on local dev and on Siteleaf.) Now that I have a way to reliably test favicon switching on Safari, I think I have a better handle on the issue:

* Safari does use `favicon.ico`, but only while you are typing in the URL bar.
* For both the pinned tab icon and the icon it uses when you have "Show website icons in tabs" enabled, it uses your `<link rel="mask-icon">` if available, in our case `safari-pinned-tab.svg`.
* If I remove the `<link rel="mask-icon">` reference, Safari falls back to `favicon.ico`.

@cunning-folk Sorry to ask this after I already told you that `favicon.ico` was the only file I needed.  I didn't know the above at the time...  Could you give me a new `safari-pinned-tab.svg` with the same sizing adjustments you made to the `favicon.ico`?  I think that would be ideal.  Failing that, I can just remove the `<link rel="mask-icon">` tag and make Safari use `favicon.ico`.

**Comment by cunning-folk** [comment]
try this one.
[wholeview-logo-avatars_wholeview-avatar copy.svg.zip](https://github.com/CunningFolkDev/elevate360_website/files/3192921/wholeview-logo-avatars_wholeview-avatar.copy.svg.zip)

**Comment by jeremylenz** [comment]
@cunning-folk That fixes the size issue!  Thanks!
