### ISSUE TITLE
'Our Vision' 50/50 content area broken

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#18]
<img width="1084" alt="screen shot 2018-11-07 at 1 07 43 pm" src="https://user-images.githubusercontent.com/31627480/48157920-3b203500-e28e-11e8-935e-bb773839ee36.png">

1. 'Our Vision' content is seems pushed to the right of the page
2. There is white space around the 'Our Vision' image that should not be there. Sort of broken.

**Comment by cunning-folk** [comment]
<img width="1084" alt="screen shot 2018-11-07 at 1 07 43 pm" src="https://user-images.githubusercontent.com/31627480/48157920-3b203500-e28e-11e8-935e-bb773839ee36.png">

1. 'Our Vision' content is seems pushed to the right of the page
2. There is white space around the 'Our Vision' image that should not be there. Sort of broken.
3.

**Comment by lukemiller** [comment]
fixed
