### ISSUE TITLE
Logo size

### ISSUE THREAD

**Issue by jeremylenz** [CunningFolkDev/elevate360_website#184]
_7. The logo on the bottom looks much smaller than the elevate logo above quick links in the gray section._

**Comment by jeremylenz** [comment]
@cunning-folk This is the same issue as the favicon sizing issue - the element is the same size as the elevate360 logo was, but it doesn't fill the canvas.   Can you pls make a new `logo-bug.svg` with the size fixes?

(Side note: Oddly, it looks like `logo.svg` in the header doesn't have the same problem.)

**Comment by cunning-folk** [comment]
[SVG.zip](https://github.com/CunningFolkDev/elevate360_website/files/3193116/SVG.zip)
@jeremylenz try the attached file

**Comment by jeremylenz** [comment]
@cunning-folk perfect!  Thanks
