### ISSUE TITLE
Add Popup

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#187]
We are changing our name to better reflect our mission, our vision and our future!
We are pleased to announce that Elevate360 is now Wholeview Wellness.

Our name change allows us to better reflect our efforts to take a broad and comprehensive approach to each patient including their entire life circumstances during our assessment and treatment planning.

Rest assured – we will continue to provide the expert addiction and mental health care you have come to expect from our team of dedicated clinicians.

**Comment by cunning-folk** [comment]
@jeremylenz I need to tighten this up, bit does this design seem doable?

<img width="860" alt="Screen Shot 2019-05-16 at 5 16 59 PM" src="https://user-images.githubusercontent.com/31627480/57892999-75026300-77fe-11e9-8422-1847e0d6a239.png">

**Comment by jeremylenz** [comment]
Yeah totally!

--
Jeremy Lenz
646-248-6678
Medium | Github | LinkedIn | Twitter

**Comment by cunning-folk** [comment]
@jeremylenz how would you like me to deliver the file? Do you have sketch? Zeplin?

**Comment by jeremylenz** [comment]
Let’s do Zeplin, I can use the free plan :)

--
Jeremy Lenz
646-248-6678
Medium | Github | LinkedIn | Twitter

**Comment by cunning-folk** [comment]
@jeremylenz I uploaded a design to zeplin

Feel free to tweak as needed!

**Comment by jeremylenz** [comment]
@cunning-folk Check out the current preview on the wholeview Siteleaf to see the popup so far.  Thoughts?

**Comment by jeremylenz** [comment]
- [ ] Center copy in right half of popup
- [ ] Make body text smaller
- [ ] Header color - should be slate gray color
- [ ] Copy should be slate gray color
- [ ] Use same copy as Zeplin - edit out half of 2nd sentence
- [ ] Add box shadow to logo container
```css
box-shadow: inset 0 0 10px 7px rgba(0, 0, 0, 0.02);
background-color: #ffffff;
```
- [ ] Desktop - even space to left and right of logo
- [ ] Mobile - Shrink logo, add padding
- [ ] X button should have transparent background
- [ ] Fix X button spacing
