### ISSUE TITLE
'Our Vision' Heading below content

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#19]
![image-1](https://user-images.githubusercontent.com/31627480/48158419-b2a29400-e28f-11e8-80df-d5eb373082f1.jpeg)

The 'Our Vision' header needs to be above the paragraph content.

**Comment by lukemiller** [comment]
fixed

**Comment by cunning-folk** [comment]
still seeing this on chrome. maybe you didnt deploy.
