### ISSUE TITLE
Need new social links

### ISSUE THREAD

**Issue by jeremylenz** [CunningFolkDev/elevate360_website#191]
Need to confirm new social urls for 
- [x] Twitter,
- [x] Facebook, and
- [ ] Instagram
 after the wholeview name change.

**Comment by cunning-folk** [comment]
@jeremylenz I'm on it

**Comment by cunning-folk** [comment]
https://www.facebook.com/wholeviewwellness/?modal=admin_todo_tour

**Comment by cunning-folk** [comment]
one more:
https://twitter.com/WholeviewNYC

**Comment by jeremylenz** [comment]
Also added LinkedIn.  html_proofer shows a failed link with `999 no error` due to [this issue](https://github.com/gjtorikian/html-proofer/issues/215).
