### ISSUE TITLE
Connect website to Mailchimp

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#195]
@jeremylenz can you paste this code block into the head?

The client wants to connect the website at wholeview.co to Mailchimp.

`<script id="mcjs">!function(c,h,i,m,p){m=c.createElement(h),p=c.getElementsByTagName(h)[0],m.async=1,m.src=i,p.parentNode.insertBefore(m,p)}(document,"script","https://chimpstatic.com/mcjs-connected/js/users/67197f5bd0a1decb3d98c97cc/45441f86db86d56e16521407b.js");</script>`

I'm not sure what features this offers, but may as well do it?

https://mailchimp.com/help/about-connected-sites/?_ga=2.128070154.749966289.1560191032-199000959.1558473109

**Comment by jeremylenz** [comment]
@cunning-folk okay done!
