### ISSUE TITLE
Elevate360.com redirect

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#197]

**Comment by cunning-folk** [comment]
@jeremylenz I know you are full-time, but when you have a moment can you help me figure something out?

I had an IT guy set up the MX records for elevate360.com. However, I need to stop the domain from redirecting to wholeview.com. I do not see any forwarding setting active in Google domains. Any ideas on how to fix this? 

I attached screenshot of the dashboard.

<img width="953" alt="Screen Shot 2019-08-14 at 12 04 56 PM" src="https://user-images.githubusercontent.com/31627480/63044944-8bb36700-be8c-11e9-8136-05f1d27c18ab.png">

<img width="780" alt="Screen Shot 2019-08-14 at 12 08 09 PM" src="https://user-images.githubusercontent.com/31627480/63044946-8bb36700-be8c-11e9-84a7-2ab3993e4b56.png">

**Comment by jeremylenz** [comment]
@cunning-folk The domain is Google Domains, but the DNS is actually handled by [Amazon Route53](https://console.aws.amazon.com/route53/home?region=us-east-1#).

I see hosted zones in there for elevate360 and for wholeview.co, but not wholeview.com.

**Comment by jeremylenz** [comment]
@cunning-folk I think I may have misread you before.. are you trying to stop `elevate360.com` from redirecting to `wholeview.co` ?  If so I think that's actually set up in the settings for the S3 bucket for elevate360.
