### ISSUE TITLE
Group Psychotherapy Not Posting Content

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#199]
https://manage.siteleaf.com/sites/5cbe1b4fd60bac49a83f76d8/collections/group-psychotherapy

Ideas?

Again, if you have time please let me know! Thanks

**Comment by jeremylenz** [comment]
I'm guessing this issue will go away once #198 is resolved.  If not, I would need some more specific info.

**Comment by jeremylenz** [comment]
@cunning-folk Were you able to try this again?  Let me know if everything is working ok.

**Comment by cunning-folk** [comment]
Seems like all is well!
