### ISSUE TITLE
Find/Replace on Wholeview Website

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#200]
@jeremylenz When you have some time can you please sweep through Wholeview and do a find and replace of specific copy?

We need “Wholeview Wellness” to supplant 'Wholeview'

Let me know what questions you may have 😁

**Comment by cunning-folk** [comment]
@jeremylenz I dont want to make a presumption where you are on this effort. The client noticed (thankfully) that you corrected the body copy. They brought to attention the need to also change some of the header language. 
![unnamed-1](https://user-images.githubusercontent.com/31627480/66405751-d262a080-e9a7-11e9-83b2-48dd5ac46572.jpg)
![unnamed](https://user-images.githubusercontent.com/31627480/66405752-d2fb3700-e9a7-11e9-8655-ddd897a9b9f4.jpg)

**Comment by jeremylenz** [comment]
@cunning-folk Siteleaf was having some issues; it's possible they're not seeing the most up-to-date copy.  I'll see if I can get an update and also take another look.

**Comment by cunning-folk** [comment]
Gotcha!

**Comment by jeremylenz** [comment]
@cunning-folk Let me know if this issue can be closed or if we're still missing some

**Comment by jeremylenz** [comment]
this is complete; Closing
