### ISSUE TITLE
Wholeview Wellness Banners

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#202]
*via client-*

We are trying to secure our trademark and need to add the words Wholeview Wellness to the bottom banner of our website.   Can you add the words “Wholeview Wellness” near the Wholeview “w” mark on the bottom banner for the entire website?  In order to show that we are using our trademark, we need it to be part of the banner, (not just in the text).

*via Peter*

I am waiting to hear back about how many other parts of the website might need this treatment.

**Comment by cunning-folk** [comment]
@jeremylenz want to scop this for me. We have the approval to move forward. I'm not sure I have time to get you the graphics today tho...

If you feel good about formatting the graphics, let me know!

**Comment by jeremylenz** [comment]
I can add the Wholeview Wellness text next to the logo in the site footer, like this:

<img width="631" alt="Screen Shot 2020-01-08 at 1 12 33 PM" src="https://user-images.githubusercontent.com/22042343/72004066-a1993e00-3218-11ea-89ee-0067033b36b2.png">

Is that what you want?  Or it needs to be an image?

**Comment by cunning-folk** [comment]
@jeremylenz all html is totally fine.

see if you can get it lined up with the logo mark similar to the image I have attached. 

I think it should all be lowercase also.

Let me know if you think this will work

<img width="935" alt="Screen Shot 2020-01-08 at 12 45 27 PM" src="https://user-images.githubusercontent.com/31627480/72010328-de633600-3214-11ea-9cfb-4468717e373c.png">

**Comment by jeremylenz** [comment]
```css
.text {
            font-weight: lighter;
            margin-left: 10px;
            align-self: flex-end;
            text-transform: lowercase;
            letter-spacing: 1.5px;
        }
```
I was able to get it pretty close with `align-self: flex-end;` and letter spacing of 1.5.
<img width="401" alt="Screen Shot 2020-01-08 at 2 56 15 PM" src="https://user-images.githubusercontent.com/22042343/72011061-0bb8df80-3227-11ea-840a-596b1ef50ed5.png">

**Comment by cunning-folk** [comment]
Looks great to me!

**Comment by jeremylenz** [comment]
cool, published :sunglasses:
