### ISSUE TITLE
Legitscript addition

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#206]

**Comment by cunning-folk** [comment]
I'm not sure where this icon should go. I think LegitScript is a certification for health centers to certify their ads as non-spam. 

https://www.legitscript.com/service/certification/addiction-treatment/

via Client:

To display your LegitScript seal of approval on your website, please include the following HTML code in your web pages at the position where the seal should be displayed:

<script src="http://static.legitscript.com/seals/4426774.js"></script>
If your site is secured with an SSL certificate, use the following version instead to avoid security warnings:

<script src="https://static.legitscript.com/seals/4426774.js"></script>
This HTML code instructs your visitor's browser to request a small piece of Javascript code from our servers, which in turn will fetch and display the seal image. The seal will be linked to your website's validation page at legitscript.com.

Both the Javascript snippet and the seal image are served from our fast and reliable content delivery network to ensure that your page rendering performance is not affected.

The seal is 140 pixels wide and 100 pixels high. We do not recommend scaling the image via CSS as it may become hard to read at smaller sizes. Here is a sample:

**Comment by jeremylenz** [comment]
I put it in the site footer for now.  If that works for you then I'll try to make it look better on mobile (needs some margin adjustments).  Or let me know where else it should go.

<img width="504" alt="Screen Shot 2020-02-16 at 2 23 48 PM" src="https://user-images.githubusercontent.com/22042343/74611240-f9ed1680-50c7-11ea-8e3f-8de435c161a6.png">

**Comment by jeremylenz** [comment]
@cunning-folk How does the location look to you?

**Comment by jeremylenz** [comment]
closing, location is OK
