### ISSUE TITLE
Dependency Error: 

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#211]
Client reports that updates arent rendering. I see an error in the publish dropdown. Have a look?

Dependency Error: Yikes! It looks like you don't have kramdown-parser-gfm or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- kramdown-parser-gfm' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! (RuntimeError)

**Comment by jeremylenz** [comment]
@cunning-folk thanks for bringing it up!  Looks like `kramdown`, one of the dependencies of Jekyll, extracted the `kramdown-parser-gfm` functionality to its own gem recently which broke Jekyll.  I've manually added `kramdown-parser-gfm` to our Gemfile.  Publishes are succeeding again.  

When Jekyll is updated with the correct dependencies, we'll be able to drop `kramdown-parser-gfm` from our Gemfile once again.  Until then, explicitly requiring it should resolve our issue for now.
