### ISSUE TITLE
Formcarry Fix

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#212]
Jeremy, can you let me know if this is possible?

_via client:_
**Background:**
We get emails from the website via formcarry.
We want to know how they found us on the website so we can keep track.
Is it possible for you to add under our emails from the website

### How did you hear about us?

possible form items:

Addiction Psychiatrist
Independent Therapists
Online Marketing
Addiction Clinics
Recovery Coach
Concierge MD
Corporations
Advocacy Agency
Start Your Recovery
Internal Medicine
Sober Home
Current Patient
Prior Patient
High-end Health Advisory
Urgent Care
Universities
ZocDoc
Bing
Yelp
Psychology Today
ZenCare
Google Search

**Comment by jeremylenz** [comment]
@cunning-folk Ok, I've added the dropdown to the form.  I managed to get the styling to fit in with the rest of the site pretty well, thanks to this [article on CSS Tricks](https://css-tricks.com/the-current-state-of-styling-selects-in-2019/) I found.  I took their styles and adapted the colors, fonts and border to the Wholeview site.

The client can configure / reorder the options in Siteleaf under Settings -> formcarry_how_did_you_hear_options.

**Comment by cunning-folk** [comment]
@jeremylenz when you have time, can you please change the form options to: (I'm not so sure how long 'specify' would take?)

Let me know how long you think these changes might take you. cheers

Google Search
Bing
Yelp
Psychology Today
ZocDoc
ZenCare
Psychiatrist
Therapist
Addiction Clinic
Recovery Coach
Sober Home
Primary Care Physician
Current Patient
Past Patient
Other: Please Specify
