### ISSUE TITLE
Light research on 'Intercom'

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#213]
@jeremylenz 

I have a demo with[Intercom](https://www.intercom.com/) on Monday.

https://www.intercom.com/help/en/

can you spend a little time figuring out whether or not Intercom would work on the static website you built for Wholeview?

**Comment by jeremylenz** [comment]
@cunning-folk I watched a few of their videos and reviewed a couple articles.  Looks like it'd be pretty straightforward to install (the instructions I would be following are [here](https://www.intercom.com/help/en/articles/167-install-intercom-on-your-website-and-chat-with-logged-out-visitors))

However I honestly don't see much potential for benefit to their business.  It seems like it's oriented around medium-to-large companies who have customer service teams or more complex web apps.

**Comment by cunning-folk** [comment]
I hear you that this app might be a bit overkill. Do you have any suggestions for a chat or contact option for their website that renders in a similar way? Basically a way for a potential therapeutic client to be able to easily make contact. I think they feel many of their clients are in the throes of a substance abuse issue and a traditional contact form may not be cutting it.

**Comment by jeremylenz** [comment]
Closing for now; please reopen if we need more research done
