### ISSUE TITLE
New Homepage Callout

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#215]
@jeremylenz more scoping:

I’d also like to more prominently display that we are available through teletherapy. Can you add this language to the first webpage?  What do you think about using the attached image along with the words below? 
Serving you safely through telehealth during the COVID-19 Crisis

Our therapists are ready to meet you from the safety and convenience of your home through telehealth sessions.  Contact us for more information or to make an appointment.

 Examples she liked:

https://inter-care.com/
https://www.freedominstitute.org/
https://www.parallaxcenter.com/
https://motivationandchange.com/

**Comment by jeremylenz** [comment]
@cunning-folk can you attach the image? Or was it just the links?

**Comment by cunning-folk** [comment]
Its a horrific image of a woman crying.

I’ll find something less desperate 😂

**Comment by cunning-folk** [comment]
she wants Option A

Option A - Change the front banner from "Here's how we're responding to the COVID-19 crisis" to "Serving you safely through telehealth during the COVID-19 Crisis".  And change the button to say "Learn More".  The button would still link to the existing COVID statement at https://wholeview.co/covid/.  Very easy, just the 1/2 hr. minimum

**Comment by jeremylenz** [comment]
How's this?

<img width="1610" alt="Screen Shot 2020-11-01 at 12 08 17 PM" src="https://user-images.githubusercontent.com/22042343/97809469-12439800-1c3b-11eb-8228-d2056d37ca54.png">

**Comment by cunning-folk** [comment]
thats good.

Like.

**Comment by jeremylenz** [comment]
Work completed as of 12 Nov.
