### ISSUE TITLE
Contact Page link

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#216]
Also, when they click on contact us, can you lead them to the https://wholeview.co/about-us/contact/ page.  I’m wondering if it is possible for you to reduce the blank space on the Contact Us page so that they can see the form to complete without having to scroll down? I’m afraid that people may miss it.
 
More, lol @jeremylenz

**Comment by cunning-folk** [comment]
via client:

We aren't sure what you mean by:

"Also, when they click on contact us, can you lead them to the https://wholeview.co/about-us/contact/ page “

**

> I just meant that in the text below when folks click on Contact us, that there is a hyperlink to the contact page. Maybe that was so obvious that it was confusing.

**

Serving you safely through telehealth during the COVID-19 Crisis

Our therapists are ready to meet you from the safety and convenience of your home through telehealth sessions.  Contact us for more information or to make an appointment.

**Comment by jeremylenz** [comment]
that cleared it up, thanks!


On October 31, 2020, Peter McEwen <notifications@github.com> wrote:
> via client:
>
> We aren't sure what you mean by:
>
> "Also, when they click on contact us, can you lead them to the
> <https://wholeview.co/about-us/contact/> page “
>
> **
>
> > I just meant that in the text below when folks click on Contact us,

> > that there is a hyperlink to the contact page. Maybe that was so
> > obvious that it was confusing.
> >
>
> **
>
> Serving you safely through telehealth during the COVID-19 Crisis
>
> Our therapists are ready to meet you from the safety and convenience

> of your home through telehealth sessions. Contact us for more
> information or to make an appointment.
>

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/CunningFolkDev/elevate360_website/issues/216#issuecomment-
719947343>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AFIFNZ2QCRSWNJGM2G7XVVTSNQS3TANCNFSM4TEEISNQ>.

**Comment by jeremylenz** [comment]
Adjusted the padding on lots of elements.  Also eliminated the giant h3 that wasn't too useful, and moved the last sentence to the hero.

Previous:
<img width="1031" alt="Screen Shot 2020-11-01 at 12 59 34 PM" src="https://user-images.githubusercontent.com/22042343/97810482-2f2f9980-1c42-11eb-807b-c9739a081ae0.png">

New:
<img width="1033" alt="Screen Shot 2020-11-01 at 12 59 50 PM" src="https://user-images.githubusercontent.com/22042343/97810484-32c32080-1c42-11eb-989d-07698a38ba34.png">

**Comment by jeremylenz** [comment]
Work completed as of 12 Nov.
