### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#220]
Hi @jeremylenz 

I apologize for asking again. I promise I will get it right this time!

We need a Google Doc or something with all the creds etc for all the tech dependencies that Wholeview has floating around.

We will need to add the creds, etc for the new website as well.

Let me know how I can help you create this as you are moving on the cloning project.

**Comment by jeremylenz** [comment]
I copied the info I gathered back in March into an info card: https://github.com/CunningFolkDev/elevate360_website/projects/1#card-66326829

You can also see it here on github by going to Projects > Elevate360 PM > General Info

This is a public repo, so we probably shouldn't share secret credentials on github.  Will keep thinking about the best way to do that..

**Comment by cunning-folk** [comment]
Amazing and thank you for the reminder.

I bookmarked and won’t forget again!
