### ISSUE TITLE
'Read more' link?

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#221]
Hi J

on this URL, the entire post renders without formatting. Is there a way to post just an excerpt on this page?

https://wholeview.co/about-us/resources/

So it then renders as markdown formatted elsewhere?

This seems like a programming question, so I thought I would check with you.

**Comment by jeremylenz** [comment]
Good catch, this was a bug! In _layouts/resources.html,

```
{{ card.content }}
```

should have been
```
{{ card.excerpt }}
```

The excerpt is the first paragraph of the item's content.  So instead of the entire transcript, it now just says
```
ALLISON AUBREY, HOST:
```
If you want something more descriptive there, feel free to add a blurb or change that first line :)
