### ISSUE TITLE
Image Upload Bug

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#222]
The client is trying to add a staff member and getting the following error. I tried to manually add the image, but that didn't seem to work.

Liquid Exception: couldn't find file 'HR Headshot.webp' in `_staff/hima-reddy.markdown' Checked in these paths: /_uploads /assets/css /assets/fonts /assets/images /assets/videos /assets/audios /assets/components /assets/javascript /assets/video /assets/audio /assets/image /assets/img /assets/js /_assets/css /_assets/fonts /_assets/images /_assets/videos /_assets/audios /_assets/components /_assets/javascript /_assets/video /_assets/audio /_assets/image /_assets/img /_assets/js /css /fonts /images /videos /audios /components /javascript /audio /video /image /img /js /.jekyll-cache/assets/proxied in /_layouts/quarternary.html (RuntimeError)

**Comment by cunning-folk** [comment]
@jeremylenz I think maybe they just forgot to remove spaces from the file name.

**Comment by cunning-folk** [comment]
@jeremylenz ok, so the site now generates correctly but the new staff members do not render to the Staff page. The individual staff detail pages do render tho.

**Comment by cunning-folk** [comment]
[https://wholeview.co/about-us/our-staff/dr-felipe-castillo/](https://wholeview.co/about-us/our-staff/dr-felipe-castillo/)
[[wholeview.co/about-us/our-staff/hima-reddy/](https://wholeview.co/about-us/our-staff/hima-reddy/)

**Comment by jeremylenz** [comment]
Hi @cunning-folk 

Yeah, the original error is because the site now requires both a jpeg and a .webp copy of every image on the site.  That's what's required in order to keep the Google Lighthouse performance scores happy. I do have a gem installed that's supposed to automatically make a webp copy of any jpegs you upload, but it's kinda wonky and doesn't play well with the jekyll-assets gem. The issue may come up again. I'll see if I can think of a way to automate it to prevent this, but until then we may have to manually make a webp of any uploaded jpegs.

**Comment by jeremylenz** [comment]
Looks like you uploaded the webp images. I'm seeing all pics working properly on the Our Staff and detail pages. Closing this for now; let me know if you still see issues.

**Comment by cunning-folk** [comment]
I'm not seeing those individual staff members on this page

https://wholeview.co/about-us/our-staff/

Are you?

**Comment by jeremylenz** [comment]
Yes, I'm seeing Hima Reddy & Felipe Castillo. Those are the two, right?

<img width="1976" alt="Screen Shot 2022-06-06 at 9 06 43 PM" src="https://user-images.githubusercontent.com/22042343/172274244-2797c490-d80a-4ea7-9cf3-7e2de05ecda3.png">

**Comment by cunning-folk** [comment]
ok, must be a caching issue.

Thanks for looking!
