### ISSUE TITLE
Staff Page

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#224]
hi @jeremylenz 

the client tried to upload a new staff member. it broke the website. 

I did what I could to fix the issue by deploying the images to master manually.

The thumb on https://wholeview.co/about-us/our-staff/ is still rendering the wrong image.

The image on the main staff page is correct: https://wholeview.co/about-us/our-staff/amy-trachter/

<img width="731" alt="Screen Shot 2022-07-25 at 5 01 56 PM" src="https://user-images.githubusercontent.com/31627480/180888864-7baa375c-d81e-4f51-a459-ea19320d0a5a.png">

I reached out to Siteleaf to try to get your community post bumped. If we don't hear back this week we should probably roll back the webp fix. The real issue is that frequent errors like this erode trust, and I don't think that would be a good way to set the path.

Let me know what you think. Sorry for the trouble!

**Comment by cunning-folk** [comment]
Also of note. The thumbnail on the staff page renders correctly on the staging website.

**Comment by jeremylenz** [comment]
Hey @cunning-folk 

When the site is published it goes through 3 stages:
1. Siteleaf updates our S3 bucket which publishes at http://www.wholeview.co.s3-website-us-east-1.amazonaws.com/
2. Cloudfront propagates that to the CDN at https://d3ao09uutrogft.cloudfront.net/
3. the domain https://wholeview.co points to the Cloudfront distribution.

When I checked a couple hours ago, both pics were displaying properly on the S3 bucket, but hadn't yet propagated to Cloudfront. That propagation can take 0-2 hours (I think?)

Now it looks like you've unpublished that staff entry. But if you publish it again and it looks okay on the S3 site I linked above (you may have to log in to AWS- not sure), I'd say everything is fine.

I'll send an update separately on my overall efforts re: this problem..

**Comment by cunning-folk** [comment]
Ah ok.

Its the propagation issue that is my frequent disconnect.

Thanks for pointing that out.
