### ISSUE TITLE
Nav menu closes prematurely

### ISSUE THREAD

**Issue by jeremylenz** [CunningFolkDev/elevate360_website#228]
It looks like what's happening is that there's a [mouseleave event](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseleave_event) on the `<nav>` which is triggering the menu close. This would normally be by design, except it seems to be triggered whenever I move my mouse cursor to any of the `<a>` tags for the main nav titles ('About Us', 'Services', etc.)

**Comment by jeremylenz** [comment]
@cunning-folk This should be fixed now.  It was another breakpoint I needed to change (this time in the JavaScript.)

**Comment by cunning-folk** [comment]
Incredible. Thank you!!
