### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#26]
<img width="1060" alt="screen shot 2018-11-07 at 4 20 44 pm" src="https://user-images.githubusercontent.com/31627480/48167503-1a190d80-e2a9-11e8-8440-befc6a3144fc.png">

Can we please bring the contact form upward and shrink the 'Contact Us' portion of the page? If you need a specific design let me know.

**Comment by lukemiller** [comment]
done
