### ISSUE TITLE
Fix Share Card - SEO Bug

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#29]
Right now, an image isn't rendering in the card view on [HeyMeta](http://www.heymeta.com/) nor [Twitter Validator](https://cards-dev.twitter.com/validator )

I would like to make sure that an image is showing up when someone shares the website. I think there is already logic for the blog posts to render an image when shared. 

I also would like to submit a sitemap to Google Webmaster tools. 

Here are resources to help

[SEO Siteleaf](https://www.siteleaf.com/blog/seo-with-jekyll-siteleaf/)
[SEO Tag - Jekyll](https://github.com/jekyll/jekyll-seo-tag) (already installed)
[Sitemap](https://learn.siteleaf.com/themes/sitemaps-and-feeds/)(not installed)

**Comment by gblakeman** [comment]
@cunning-folk It looks like Luke already added a plugin for the sitemap (#2). The address you should submit to Google’s webmaster tools is: https://elevate360.com/sitemap.xml

**Comment by cunning-folk** [comment]
@gblakeman I added the XML URL to Google Webmaster tools. Thanks!
