### ISSUE TITLE
Dropdown Menus

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#30]
We will need drop-down menus for tertiary sections of the website. Right now, the navigation only exposes top-level links.

Can we get a sense of how this needs to be done? I have attached a sitemap.

I'll add detail to this ticket after we have a general sense of the difficulty.

[Elevate360_Sitemap.pdf](https://github.com/CunningFolkDev/elevate360_website/files/2581702/Elevate360_Sitemap.pdf)

**Comment by gblakeman** [comment]
@cunning-folk The Siteleaf side of this looks pretty straightforward: you create a new page and then, from the [Pages](https://manage.siteleaf.com/sites/5b858a6b93a57a4734333f6c/pages) menu, drag it “under” the page you want to be the parent.

As far as the work on my end, it’ll depend a bit on the design and how you want it to work, but I would estimate roughly 3-5 hours of work.

**Comment by cunning-folk** [comment]
I think you can handle the design. I am happy to comp it up if you prefer. 

I am intrigued by the idea of using something like the top-level navigation used at:

https://www.simple.com/
or
https://mailchimp.com/

Maybe we should quickly review the sitemap and make a determination?

**Comment by gblakeman** [comment]
Finished in #60.
