### ISSUE TITLE
Validate site with Google?

### ISSUE THREAD

**Issue by gblakeman** [CunningFolkDev/elevate360_website#33]
Does the site still need to be validated with Google’s Webmaster Tools? Some info [here](
https://www.siteleaf.com/blog/seo-with-jekyll-siteleaf/#using-the-jekyll-seo-tag-plugin) for the implementation.

**Comment by gblakeman** [comment]
@cunning-folk If this still needs to happen, get me the ID number that Google wants us to validate and I’ll add that to the site config.

**Comment by cunning-folk** [comment]
ok, this issue can be closed. thanks!
