### ISSUE TITLE
SEO: Improve Page Titles

### ISSUE THREAD

**Issue by gblakeman** [CunningFolkDev/elevate360_website#35]
For the sake of SEO, the page titles should probably contain the company name, and perhaps a tagline.

Right now they’re just the base page title:
![screen shot on 2018-11-14 at 16-57-57](https://user-images.githubusercontent.com/867428/48522746-b0f84380-e82e-11e8-98bd-5d685710230b.png)

**Comment by gblakeman** [comment]
@cunning-folk This is an easy update. Let me know if you want me to take care of it.

**Comment by cunning-folk** [comment]
totally agree. Let me know if you want me to compile a list or if you feel like you can tackle it.

**Comment by gblakeman** [comment]
@cunning-folk Let me tackle it first (I have a pretty standard pattern I use for most sites), and then you can suggest improvements if necessary.

**Comment by cunning-folk** [comment]
@gblakeman thanks for taking care of this. Go full steam
