### ISSUE TITLE
Hook up Newsletter Sign-up Form

### ISSUE THREAD

**Issue by gblakeman** [CunningFolkDev/elevate360_website#50]
The footer’s Newsletter sign-up form was styled in #47, but still needs to be hooked up to Mailchimp.

**Comment by cunning-folk** [comment]
@gblakeman I made a new list in mailchimp called "Contact Elevate360 Wellness" to route contact form mail.

If you have a better idea, I am totally open to it. The strategy has been to use Mailchimp to circumvent the use of another 3rd party service to handle email. Jekyll doesn't natively support email 'post' etc

**Comment by gblakeman** [comment]
@cunning-folk Is the purpose to collect email addresses for a list? Or to provide a “Contact Form”? Mailchimp is great for the former and I recommend [Formcarry](https://formcarry.com) for the latter.

**Comment by gblakeman** [comment]
@cunning-folk Am I ok to use Mailchimp on this? You mentioned somewhere about needing to move away from Mailchimp, but we still need something to collect email addresses in the interim…

**Comment by cunning-folk** [comment]
I think we’ll have to setup a traditional contact form.

The mailchimp option doesnt seem well fitted to use as a traditional
contact form. For instance if someone posts to the contact form (mailchimp)
and they are already in the mailing list, mailchimp throws an error. Im
open to ideas on this!

**Comment by gblakeman** [comment]
I’m talking about the Newsletter Signup form in the Footer (currently hidden). That seems like it should go to Mailchimp (or some sort of email newsletter service).

As for the Contact form, I wrote a whole response in #101 yesterday and it seems like Github ate it. I’ll add it again.

**Comment by cunning-folk** [comment]
Oh. For joining the email list Mailchimp is a yes! My bad!

**Comment by gblakeman** [comment]
Newsletter sign-up is in `production`. I confirmed that I could sign up from the footer. 🙌
