### ISSUE TITLE
Call to Action Banner Height // Desktop

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#52]
<img width="1323" alt="screen shot 2018-11-17 at 2 24 16 pm" src="https://user-images.githubusercontent.com/31627480/48665917-9c0cf180-ea74-11e8-9ff8-592b86b79e8f.png">

@gblakeman the client requested that the secondary call to action banner (avocado in color) gets a different treatment.

If you have time to narrow the heigh, make the type size a bit smaller and perhaps take the line height down a bit, that would be great.

In the end, this call to action area needs to be shorter in height. Happy to chat!

**Comment by lukemiller** [comment]
@gblakeman I've split this off into it's own include.  I think I can merge that into master w/o impacting anything on production.

**Comment by lukemiller** [comment]
k - this is set up in _includes/section-callout.html

the same block gets rendered a few times in the services section (with a few font-size overrides) so just be mindful of that.

**Comment by cunning-folk** [comment]
Lets do something in the neighborhood of what I drew in this comp?

https://zpl.io/25wQnY0

**Comment by cunning-folk** [comment]
![homepage](https://user-images.githubusercontent.com/31627480/49041835-8d64bf80-f183-11e8-9895-0c468c13a230.jpg)

@gblakeman I added a rough comp to the desktop_prod sketch file. I am open to any design augmentation that you propose. I agree with the client that the green bar has an excessive height.

https://www.dropbox.com/s/sno8rnsdov12t6u/desktop_prod.sketch?dl=0

**Comment by gblakeman** [comment]
Before / After GIF:

![elevate-cta-before-after](https://user-images.githubusercontent.com/867428/49111446-011ad100-f245-11e8-8e4c-a9c3d1669c4c.gif)
