### ISSUE TITLE
'Learn More' Sitewide

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#68]

**Comment by cunning-folk** [comment]
<img width="407" alt="screen shot 2018-11-26 at 2 02 46 pm" src="https://user-images.githubusercontent.com/31627480/49041989-095f0780-f184-11e8-9453-6d730f17fb93.png">

I have noted that the 'learn more' copy sitewide is right-justified. 

If there is a technical reason we should continue to this, let me know.

Otherwise, let's move the 'learn more' link to the right of the copy block.

**Comment by gblakeman** [comment]
@cunning-folk This should be taken care of now. Let me know if I missed any!
