### ISSUE TITLE
Call to Action Banner Height // Mobile

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#69]

**Comment by cunning-folk** [comment]
![img_4506](https://user-images.githubusercontent.com/31627480/49042779-517f2980-f186-11e8-8124-5bc9f9c8c236.png)

The mobile version, like desktop, is a bit tall. The text is also the wrong color.

@gblakeman If you need a mockup let me know. I feel as though you could make this look nicer without my input.

**Comment by gblakeman** [comment]
@cunning-folk Any reason not to follow the mobile design comp? Seems like a good version to me.

![elevate360-mobile-cta](https://user-images.githubusercontent.com/867428/49103575-9069b980-f230-11e8-8a89-0c19399b486e.png)
