### ISSUE TITLE
Trainings Subpage

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#71]

**Comment by lukemiller** [comment]
I think this is handled by #70

**Comment by gblakeman** [comment]
@cunning-folk I’m not sure what still needs to be done on this issue. Could I get some more detail?

**Comment by cunning-folk** [comment]
@gblakeman This was a ticket to create individual pages for the various Training offerings. Tight now, there are modals for the individual offerings in 'Services' and 'Trainings'. However, there are designs for each individual offering.

Staging: https://5b858a6b93a57a4734333f6c.preview.siteleaf.com/trainings-for-clinicians/

These sub-items have a design for each.

https://zpl.io/bJZ3Wj6

What are your thoughts on making individual pages? I'm not sure from a timing strategy whether or not to move forward with the work. Thoughts? If you don't think this hurts any SEO advantage then I guess we can leave as is.

**Comment by gblakeman** [comment]
Ahh, gotcha.

From a content/SEO standpoint, I think it's much better to have separate pages.

That page design definitely needs a back button or breadcrumb nav of some kind, though. 🤔

**Comment by cunning-folk** [comment]
@gblakeman ok, let me know if this is something you want to tackle? If not, I can maybe send over to Jeremy. 

I agree that having a page dedicated to a content block sets the client up for SEO success.

**Comment by gblakeman** [comment]
Addressed in #122
