### ISSUE TITLE
Move 'How Are We Different' text block

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#77]
We need to move around the main text/image blocks on the homepage

**Comment by cunning-folk** [comment]
The 'How are we different block needs to be moved in the order outlined in these comps

https://zpl.io/bWk5K17

https://zpl.io/VkELOr8

**Comment by cunning-folk** [comment]
@gblakeman If you get time to tackle this issue later in the week, please do so. If not, hopefully Luke can take it.

**Comment by lukemiller** [comment]
I'm on this

**Comment by lukemiller** [comment]
done
