### ISSUE TITLE
Review Header Ideas

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#78]
@gblakeman 

Do you think these headers would be better candidates for the hero image?

https://zpl.io/bWk5K17

https://zpl.io/VkELOr8

**Comment by gblakeman** [comment]
@cunning-folk I think the image you have is fine. It just needed some tweaks. Here’s how it’s looking in #80 (still a WIP): https://d.pr/v/8ibusl

**Comment by cunning-folk** [comment]
sounds good. Closing this one.
