### ISSUE TITLE
Make 'Learn More' on Homepage Live

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#79]

**Comment by cunning-folk** [comment]
<img width="335" alt="screen shot 2018-11-27 at 2 51 51 pm" src="https://user-images.githubusercontent.com/31627480/49113969-35e25480-f254-11e8-9a0e-3a8b66bce437.png">

Exceptional Addiction Care:
https://elevate360.com/about-us/

How are we different:
https://elevate360.com/why-elevate360/

Compassionate Care, Effectively Done:
https://elevate360.com/services/

Professional Treatment That Works:
https://elevate360.com/treatment-programs/

**Comment by gblakeman** [comment]
This should be addressed in the next deploy.

<img width="1438" alt="screen shot 2018-12-05 at 11 30 42 am" src="https://user-images.githubusercontent.com/867428/49538912-54160900-f881-11e8-9cc2-badcb55e4f30.png">
