### ISSUE TITLE
Eliminate render-blocking JavaScript and CSS in above-the-fold content

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#82]
I rant a Google test and it returned two issues. The image compression and this render blocking issue. Let me know if you have any thoughts on this.

**Comment by lukemiller** [comment]
I'll double check, but I don't think there are any scripts in <head> -- I think everthing is in the _script partial which is included at the end of the <body>.

**Comment by gblakeman** [comment]
Yeah, I have no idea what would block rendering. 🤷🏻‍♂️

**Comment by gblakeman** [comment]
Added #83 – I think Google just wants the `async` attribute added to the script tag. Nothing is actually blocking the site from rendering. A false positive in their testing tool, imho.

I bet the poor score is mostly the lack of image optimization.

If you’re using [this tool](https://testmysite.thinkwithgoogle.com), keep in mind that it’s mostly a marketing site for their stupid AMP pages.

**Comment by lukemiller** [comment]
fine w/ me
