### ISSUE TITLE
Add Address to Footer.

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#94]
Client notes that address is nowhere on the website (oops).

**Comment by cunning-folk** [comment]
<img width="796" alt="screen shot 2018-11-29 at 3 05 46 pm" src="https://user-images.githubusercontent.com/31627480/49255175-7246b980-f3e8-11e8-8d91-aa52e030c617.png">

@lukemiller something like this work?

**Comment by cunning-folk** [comment]
https://zpl.io/VkELOr8

Zeplin Link.

**Comment by lukemiller** [comment]
done

**Comment by cunning-folk** [comment]
@lukemiller I'm not seeing this on staging. Cheers

**Comment by lukemiller** [comment]
<img width="1480" alt="screenshot 2018-11-30 13 29 44" src="https://user-images.githubusercontent.com/220137/49313331-1e99a600-f4a4-11e8-9219-b2e30bba5b29.png">

**Comment by cunning-folk** [comment]
@lukemiller can we add a GEO URI to the map address in the footer?

**Comment by lukemiller** [comment]
yeah, for sure.  geo: only works for mobile though.  Maybe just a google map link?

For bonus points, we could sniff user agent & change the link accordingly.

**Comment by gblakeman** [comment]
Added a Google Maps link.
