### ISSUE TITLE
Add 'Learn More' to 'Trainings' on 'Services' landing page

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#98]

**Comment by cunning-folk** [comment]
@luke can we add a 'Learn More' link to the content block on the 'Services' home page please?

Let me know if you need a design

<img width="1378" alt="screen shot 2018-12-01 at 3 55 11 pm" src="https://user-images.githubusercontent.com/31627480/49333749-9be71880-f581-11e8-9add-0bff397aac30.png">

**Comment by gblakeman** [comment]
Included in the next deploy.

<img width="1438" alt="screen shot 2018-12-05 at 11 38 29 am" src="https://user-images.githubusercontent.com/867428/49539426-7c523780-f882-11e8-8330-d2c5cf10be37.png">
