### ISSUE TITLE
Add 'Supportive Expressive Therapy (SET)' to 'Therapies Used' pages

### ISSUE THREAD

**Issue by cunning-folk** [CunningFolkDev/elevate360_website#99]
Looks like a copy block for  'Supportive Expressive Therapy (SET)' needs to be added to 'Therapies Used'

**Comment by cunning-folk** [comment]
Supportive Expressive Therapy (SET) Supportive-Expressive Psychotherapy is a time-limited, focused psychodynamic psychotherapy that was developed for the treatment of substance use disorders. This evidence-based treatment has two main components which include techniques that support the patient in discussing their personal experiences and expressive techniques to help patients identify and work through interpersonal relationship issues. The therapist works with the patient to examine how alcohol and drugs use are used in relation to emotions and behaviors and teaches methods of problem solving that avoid the use of alcohol and drugs.

**Comment by gblakeman** [comment]
@cunning-folk Is there “Lean More” text for this one?

**Comment by cunning-folk** [comment]
@gblakeman there is no additional copy. The whole block is posted here: 

https://github.com/CunningFolkDev/elevate360_website/issues/99#issuecomment-443521350

**Comment by gblakeman** [comment]
This should be addressed in the next deploy.
